export const PERMISSIONS = {
  // HR
  VIEW_EMPLOYEES: "VIEW_EMPLOYEES",
  ADD_EMPLOYEE: "ADD_EMPLOYEE",
  EDIT_EMPLOYEE: "EDIT_EMPLOYEE",
  CREATE_EMPLOYEE: "CREATE_EMPLOYEE",

  // Leave
  APPLY_LEAVE: "APPLY_LEAVE",
  APPROVE_LEAVE: "APPROVE_LEAVE",

  // Payroll
  VIEW_PAYROLL: "VIEW_PAYROLL",
  GENERATE_PAYROLL: "GENERATE_PAYROLL",

  // Finance
  CREATE_INVOICE: "CREATE_INVOICE",
  VIEW_INVOICE: "VIEW_INVOICE",
  ADD_EXPENSE: "ADD_EXPENSE",

  CREATE_PROJECT: "CREATE_PROJECT",
  EDIT_PROJECT: "EDIT_PROJECT",

  CREATE_JOB: "CREATE_JOB",
  UPDATE_JOB: "UPDATE_JOB",

  // Admin
  MANAGE_USERS: "MANAGE_USERS",
  VIEW_ANALYTICS: "VIEW_ANALYTICS",
};