import { PERMISSIONS }
from "./permissions.js";

export const ROLE_PERMISSIONS = {

  ADMIN: [

    PERMISSIONS.VIEW_EMPLOYEES,
    PERMISSIONS.ADD_EMPLOYEE,
    PERMISSIONS.EDIT_EMPLOYEE,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.CREATE_JOB,
    PERMISSIONS.UPDATE_JOB,

  ],

  HR: [

    PERMISSIONS.VIEW_EMPLOYEES,
    PERMISSIONS.ADD_EMPLOYEE,
    PERMISSIONS.EDIT_EMPLOYEE,
    PERMISSIONS.CREATE_JOB,

  ],

  FINANCE: [

    PERMISSIONS.VIEW_PAYROLL,
    PERMISSIONS.GENERATE_PAYROLL,
    PERMISSIONS.CREATE_INVOICE,
    PERMISSIONS.VIEW_INVOICE,

  ],

  EMPLOYEE: [

    PERMISSIONS.APPLY_LEAVE,

  ],

  JOB_SEEKER: [],

};