import { PERMISSIONS } from "./permissions.js";

export const ROLE_PERMISSIONS = {
  ADMIN: Object.values(PERMISSIONS),

  HR: [
    PERMISSIONS.VIEW_EMPLOYEES,
    PERMISSIONS.ADD_EMPLOYEE,
    PERMISSIONS.EDIT_EMPLOYEE,
    PERMISSIONS.APPROVE_LEAVE,
    PERMISSIONS.VIEW_PAYROLL,
  ],

  FINANCE: [
    PERMISSIONS.CREATE_INVOICE,
    PERMISSIONS.VIEW_INVOICE,
    PERMISSIONS.ADD_EXPENSE,
    PERMISSIONS.GENERATE_PAYROLL,
  ],

  EMPLOYEE: [
    PERMISSIONS.APPLY_LEAVE,
    PERMISSIONS.VIEW_PAYROLL,
  ],
};